[package]
name = "profixy"
version = "0.2.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19.2", features = ["macros", "rt-multi-thread"] }
serenity = { version = "0.11.2", default-features = false, features = ["client", "gateway", "rustls_backend", "model"] }